# -*- coding: utf-8 -*-
{
    'name': 'Water Billing',
    'version': '1.0',
    'summary': 'Water Billing Module',
    'description': '',
    'category': 'Accounting',
    'author': 'Your Name',
    'website': 'https://example.com',
    'depends': ['base', 'account', 'contacts'],  
    'data': [
        'data/sequence_data.xml',
        'data/reading_sequence.xml',
        'data/pay_bills_sequence.xml',
        # 'views/member_views.xml',
        'views/billing.xml',
        'views/read_meter.xml',
        'views/payment_history.xml',
        'views/payment_history_reports.xml',
        'views/action.xml',
        'views/menu.xml',
        'report/payment_history_report.xml',
        'report/print_invoice.xml',
        'views/usage_graph.xml',
    ],
    'installable': True,
    'application': True, 
}